-- =========================================================
-- 2. PRODUCT PERFORMANCE - FULL DATASET
-- Grain: ProductID
--
-- Purpose:
--   - Detailed Product Analysis
--   - Product Class Mix in Tableau
--   - Product-level order frequency analysis
--
-- Export as: product_performance_full.csv
-- =========================================================

WITH product_stats AS (
    SELECT
        -- =================================================
        -- PRODUCT INFORMATION
        -- =================================================
        p.ProductID,
        p.ProductName,
        p.CategoryID,
        c.CategoryName,
        p.Class,

        -- =================================================
        -- PRODUCT SALES METRICS
        -- =================================================

        -- Total number of units sold
        SUM(s.Quantity) AS TotalQuantity,

        -- Number of distinct transactions containing
        -- this product
        COUNT(DISTINCT s.TransactionNumber) AS TotalOrders,

        -- Total revenue generated by this product
        SUM(s.Revenue) AS TotalRevenue,

        -- Average revenue generated per unit sold
        SAFE_DIVIDE(
            SUM(s.Revenue),
            SUM(s.Quantity)
        ) AS RevenuePerUnit

    FROM `sales-of-fmcg-stores.salesfmcg.vw_sales_analysis` AS s

    JOIN `sales-of-fmcg-stores.salesfmcg.products` AS p
        ON s.ProductID = p.ProductID

    JOIN `sales-of-fmcg-stores.salesfmcg.categories` AS c
        ON p.CategoryID = c.CategoryID

    GROUP BY
        p.ProductID,
        p.ProductName,
        p.CategoryID,
        c.CategoryName,
        p.Class
),

-- =========================================================
-- PRODUCT-LEVEL BENCHMARKS
-- =========================================================
median_stats AS (
    SELECT
        APPROX_QUANTILES(
            TotalQuantity,
            2
        )[OFFSET(1)] AS MedianQuantity,

        APPROX_QUANTILES(
            RevenuePerUnit,
            2
        )[OFFSET(1)] AS MedianRevenuePerUnit

    FROM product_stats
)

SELECT
    -- =====================================================
    -- PRODUCT INFORMATION
    -- =====================================================
    p.ProductID,
    p.ProductName,
    p.CategoryID,
    p.CategoryName,
    p.Class,

    -- =====================================================
    -- QUANTITY METRICS
    -- =====================================================

    -- Original number of units sold
    p.TotalQuantity,

    -- Quantity converted to million units
    ROUND(
        SAFE_DIVIDE(p.TotalQuantity, 1000000),
        2
    ) AS TotalQuantity_Million,

    -- =====================================================
    -- ORDER METRICS
    -- =====================================================

    -- Number of distinct orders containing this product
    p.TotalOrders,

    -- =====================================================
    -- REVENUE METRICS
    -- =====================================================

    -- Original revenue
    ROUND(
        p.TotalRevenue,
        2
    ) AS TotalRevenue,

    -- Revenue converted to millions
    ROUND(
        SAFE_DIVIDE(p.TotalRevenue, 1000000),
        2
    ) AS TotalRevenue_Million,

    -- Average revenue per unit
    ROUND(
        p.RevenuePerUnit,
        2
    ) AS RevenuePerUnit,

    -- =====================================================
    -- PRODUCT BENCHMARK METRICS
    -- =====================================================

    -- Median quantity across all products
    m.MedianQuantity,

    -- Median quantity converted to million units
    ROUND(
        SAFE_DIVIDE(m.MedianQuantity, 1000000),
        2
    ) AS MedianQuantity_Million,

    -- Median revenue per unit across all products
    ROUND(
        m.MedianRevenuePerUnit,
        2
    ) AS MedianRevenuePerUnit,

    -- =====================================================
    -- PRODUCT PERFORMANCE SEGMENTATION
    -- =====================================================
    CASE
        WHEN p.TotalQuantity >= m.MedianQuantity
         AND p.RevenuePerUnit >= m.MedianRevenuePerUnit
            THEN 'High Quantity - High Revenue per Unit'

        WHEN p.TotalQuantity >= m.MedianQuantity
         AND p.RevenuePerUnit < m.MedianRevenuePerUnit
            THEN 'High Quantity - Low Revenue per Unit'

        WHEN p.TotalQuantity < m.MedianQuantity
         AND p.RevenuePerUnit >= m.MedianRevenuePerUnit
            THEN 'Low Quantity - High Revenue per Unit'

        ELSE 'Low Quantity - Low Revenue per Unit'
    END AS ProductQuadrant

FROM product_stats AS p

CROSS JOIN median_stats AS m;

-- =========================================================
-- 2.2
-- =========================================================
WITH category_summary AS (
  SELECT
    c.CategoryID,
    c.CategoryName,
    AVG(v.Discount) AS AvgDiscount,
    SUM(v.Revenue) AS TotalRevenue,
    SUM(v.Quantity) AS TotalQuantity,
    SUM(v.Quantity * v.Price) - SUM(v.TotalPrice) AS RevenueLeakage
  FROM `sales-of-fmcg-stores.salesfmcg.vw_sales_analysis` v
  JOIN `sales-of-fmcg-stores.salesfmcg.products` p
    ON v.ProductID = p.ProductID
  JOIN `sales-of-fmcg-stores.salesfmcg.categories` c
    ON p.CategoryID = c.CategoryID
  GROUP BY
    c.CategoryID,
    c.CategoryName
)

SELECT
  *,
  TotalRevenue / SUM(TotalRevenue) OVER () AS RevenueShare
FROM category_summary
ORDER BY AvgDiscount DESC;
-- =========================================================
-- 2.3 PRODUCT CLASS PERFORMANCE
-- Grain: Class
-- =========================================================

SELECT
    p.Class,

    COUNT(DISTINCT p.ProductID) AS TotalProducts,

    SUM(s.Quantity) AS TotalQuantitySold,

    ROUND(SUM(s.Revenue), 2) AS TotalRevenue,

    ROUND(
        SAFE_DIVIDE(
            SUM(s.Revenue),
            COUNT(DISTINCT p.ProductID)
        ),
        2
    ) AS AverageRevenuePerProduct,

    ROUND(
        SAFE_DIVIDE(
            SUM(s.Quantity),
            COUNT(DISTINCT p.ProductID)
        ),
        2
    ) AS AverageQuantityPerProduct

FROM `sales-of-fmcg-stores.salesfmcg.vw_sales_analysis` AS s

JOIN `sales-of-fmcg-stores.salesfmcg.products` AS p
    ON s.ProductID = p.ProductID

GROUP BY p.Class

ORDER BY TotalRevenue DESC;